no_artifact_required:
  common:
    artifact_count: '>=1'
  predictions:
    artifact_count: 1
artifact_required:
  predictions:
    number_of_columns: 3
    column_not_null:
      - 0
      - 1
      - 2
    column_names:
      - OBS_DATE
      - Ticker
      - pred