backend_project_name: aix-backend-prod
website_project_name: aix-website-prod
data_stocks_project_name: aix-data-stocks
backend_user_emails:
  - enrico.testa00@gmail.com
  - airflow-prod-sa@aix-backend-prod.iam.gserviceaccount.com
zonal_exhaustion_bucket_name: aix_zonal_exhaustion
data_stocks_bucket_name: aix-data-stocks-bucket
pypi_repo_bucket_name: aix_pypi_repo
dim_cloud_resource:
  e2-micro: 1
  n1-standard-1: 2
  n2-standard-4: 3
  n1-standard-2: 4
  pd-ssd-10: 101
  gcs-transfer: 201
  big-query-compute: 301
  big-query-storage: 302
compute_zones:
  - europe-west4-a
  - europe-west4-b
  - europe-west4-c
  - europe-west3-a
  - europe-west3-b
  - europe-west3-c
  - europe-west2-a
  - europe-west2-b
  - europe-west2-c
  - europe-west1-d
  - europe-west1-b
  - europe-west1-c
  - europe-north1-a
  - europe-north1-b
  - europe-north1-c
  - europe-central2-a
  - europe-central2-b
  - europe-central2-c